export const navigation = [
  { label: 'Work', href: '/work' },
  { label: 'Services', href: '/services' },
  { label: 'How We Work', href: '/process' },
  { label: 'For Agencies', href: '/agencies' },
  { label: 'About', href: '/about' },
  { label: 'Insights', href: '/insights' },
];

export const services = [
  { slug: 'commercial-production', number: '01', title: 'Commercial production', short: 'Big-screen thinking. Every-screen impact.', description: 'Distinctive commercials that make people stop, feel, and remember. From an ambitious first idea to the final frame, we bring creative direction and production together.', items: ['TV & cinema commercials', 'Digital & YouTube campaigns', 'Brand campaigns', 'Campaign concepts & scripts'], image: '/images/vyra-hero.jpg', outcome: 'A campaign worth paying attention to.', detail: 'We develop memorable visual worlds around a clear commercial message. Every shot, edit, and sound choice works toward your audience and your objective—not a technology demo.' },
  { slug: 'product-films', number: '02', title: 'Product films', short: 'Make the product the main character.', description: 'Beautifully crafted films that turn product features into desire. Show the details, textures, and possibilities that a still image cannot.', items: ['Hero product films', 'Product visualization & animation', 'Product launches', 'E-commerce assets'], image: '/images/aura-beauty.jpg', outcome: 'From a product feature to a feeling.', detail: 'We start with accurate product references and approved claims. Then we create a visual language that makes your product unmistakable, across launch films, detail shots, and commerce-ready assets.' },
  { slug: 'brand-films', number: '03', title: 'Brand films', short: 'Stories that make your brand mean more.', description: 'Human stories, powerful visual worlds, and a point of view. Films that connect what your brand believes with what your audience cares about.', items: ['Brand storytelling', 'Corporate films', 'Campaign narratives', 'Launch films'], image: '/images/form-fashion.jpg', outcome: 'A story only your brand could tell.', detail: 'Strategy comes before spectacle. We find the human truth in your story, develop a narrative, and build an emotional visual experience around it.' },
  { slug: 'social-content', number: '04', title: 'Social content', short: 'Made for the feed. Built to stand out.', description: 'Platform-native creative with a campaign-level point of view. More than a crop of your hero film: content designed for how people actually watch.', items: ['Reels, TikTok & YouTube Shorts', 'Social cutdowns', 'Platform & audience variations', 'Short-form campaigns'], image: '/images/orange-beverage.jpg', outcome: 'One idea. Many reasons to stop scrolling.', detail: 'We plan hooks, framing, pacing, captions, and calls to action for each platform. Versioning is considered from the start so the campaign stays coherent without becoming repetitive.' },
  { slug: 'ai-production', number: '05', title: 'AI-native production', short: 'A bigger canvas for your imagination.', description: 'A human-directed, model-agnostic production approach. We select the right combination of tools for the idea—not the other way around.', items: ['Concept, image & video generation', 'Characters & environments', 'Product visualization & VFX', 'Voice, localization & post-production'], image: '/images/pulse-technology.jpg', outcome: 'Let the idea choose the technology.', detail: 'We combine creative direction, carefully selected generation workflows, compositing, editing, and sound. Human judgment stays in control at every production milestone.' },
  { slug: 'localization', number: '06', title: 'Localization', short: 'One brand. A world of connection.', description: 'Adapt campaigns for new languages, markets, and audiences while preserving the creative idea that made them work in the first place.', items: ['Arabic, English, Urdu & Spanish', 'Regional & cultural adaptation', 'Voice & subtitle versions', 'Aspect-ratio & audience variations'], image: '/images/form-fashion.jpg', outcome: 'Locally relevant. Unmistakably you.', detail: 'Localization is more than translation. We review messaging, cultural context, pronunciation, typography, and platform requirements with the relevant language specialists.' },
  { slug: 'campaign-systems', number: '07', title: 'Campaign content systems', short: 'One powerful idea. An entire content universe.', description: 'Turn a hero campaign into a connected family of assets. A repeatable production system that grows with your channels, markets, and ambitions.', items: ['Hero films & cutdowns', 'Social & product assets', 'Localized campaign versions', 'Audience variations & asset libraries'], image: '/images/orange-beverage.jpg', outcome: 'Think in campaigns, not isolated assets.', detail: 'We define a master visual system, a modular shot library, and a versioning plan. Approved creative becomes the foundation for consistent, efficient production over time.' },
];

export const processSteps = [
  { title: 'The brief', description: 'Your ambition is our starting point. We get clear on the objective, audience, message, budget, and deadline.', output: 'A clear, agreed production brief.' },
  { title: 'Creative strategy', description: 'We find the creative opportunity: the intersection of what your brand means and what your audience will care about.', output: 'The campaign direction and creative foundation.' },
  { title: 'Concept development', description: 'Two to three considered creative routes. Each with a strong idea, a distinct visual world, and a reason to exist.', output: 'Creative routes, references, and a recommended direction.' },
  { title: 'Pre-production', description: 'We make the vision tangible with scripts, storyboards, shot lists, and the visual rules that hold it all together.', output: 'An approved blueprint before production begins.' },
  { title: 'AI production', description: 'Artists and creative technologists generate, direct, refine, and control the visual material, shot by shot.', output: 'A curated, consistent collection of production assets.' },
  { title: 'Post-production', description: 'The craft that makes a film. Editing, VFX, compositing, sound design, music, and color bring the work to life.', output: 'A polished first cut with a complete sound and visual direction.' },
  { title: 'Review & refine', description: 'Human quality control and structured client feedback. We check the idea, the brand, the product, and every frame.', output: 'Approved masters, with agreed feedback incorporated.' },
  { title: 'Ready for the world', description: 'Your master film, platform-specific versions, and a clearly organized delivery package. Ready to go to work.', output: 'Final assets, technical specifications, and a delivery manifest.' },
];

export type Project = {
  slug: string; title: string; client: string; industry: string; category: string;
  tags: string[]; image: string; accent: string; description: string; brief: string;
  challenge: string; concept: string; deliverables: string[];
};
export const projects: Project[] = [
  { slug: 'beyond-the-ordinary', title: 'Beyond the ordinary.', client: 'NOMAD', industry: 'Automotive', category: 'Commercials', tags: ['Commercials', 'Automotive', 'Concept / Spec Work'], image: '/images/vyra-hero.jpg', accent: '#d8863c', description: 'An impossible landscape. An unmistakable presence. An automotive world beyond the everyday.', brief: 'Explore how an electric grand tourer could be introduced through emotion and atmosphere rather than a conventional feature list.', challenge: 'Build a cinematic world on an extraordinary scale while preserving credible automotive form, reflections, and a consistent visual identity.', concept: 'A lone vehicle at the edge of a new world. A monumental sun and an endless desert become a metaphor for possibility: the freedom to go beyond the familiar.', deliverables: ['30-second hero film concept', '15- and 6-second cutdown treatments', '16:9, 9:16 & 1:1 visual studies', 'Campaign key visuals'] },
  { slug: 'the-nature-of-radiance', title: 'The nature of radiance.', client: 'AURA', industry: 'Beauty', category: 'Product Films', tags: ['Product Films', 'Beauty', 'Concept / Spec Work'], image: '/images/aura-beauty.jpg', accent: '#d9bc62', description: 'A study in light, texture, and the quiet power of a beautifully made product.', brief: 'Create a premium skincare launch world that translates a feeling of radiance into a distinctive, ownable visual language.', challenge: 'Balance surreal material behavior with product accuracy. The packaging must remain recognizable while the environment feels expressive and alive.', concept: 'Liquid sunlight. Golden silk, glass, and soft reflections surround a single hero product, giving an everyday ritual an extraordinary sense of occasion.', deliverables: ['Hero product film treatment', 'Ingredient & texture studies', 'Social-first launch assets', 'E-commerce product visuals'] },
  { slug: 'form-in-motion', title: 'Nothing stays still.', client: 'FORM', industry: 'Fashion', category: 'Brand Films', tags: ['Brand Films', 'Fashion', 'Concept / Spec Work'], image: '/images/form-fashion.jpg', accent: '#b9b9b2', description: 'Where sculptural silhouettes meet a landscape without limits.', brief: 'Develop a fashion story built around movement, material, and the tension between a collection and its environment.', challenge: 'Maintain convincing fabric, anatomy, and styling across a visual world that would be difficult to achieve with a traditional location shoot.', concept: 'Form in motion. Architectural ivory fabric meets volcanic black terrain. The collection becomes a living sculpture, shaped by an invisible force.', deliverables: ['Fashion film concept', 'Editorial campaign stills', 'Vertical social variations', 'Art-direction reference system'] },
  { slug: 'a-taste-of-more', title: 'A taste of more.', client: 'ZEST', industry: 'Food & Beverage', category: 'Social Content', tags: ['Social Content', 'Food & Beverage', 'Concept / Spec Work'], image: '/images/orange-beverage.jpg', accent: '#ef752c', description: 'A bright burst of flavor, built to break the scroll.', brief: 'Imagine a social-first beverage launch with unmistakable shelf presence and an energetic, instantly recognizable campaign world.', challenge: 'Make a simple product feel dynamic without burying it in visual effects. Keep color, can proportions, and appetite appeal consistent across formats.', concept: 'Open a little extraordinary. Suspended citrus, sparkling liquid, and a bold orange world turn a can into a sensory experience.', deliverables: ['6- and 15-second social concepts', '9:16, 1:1 & 4:5 assets', 'Flavor variant studies', 'Product campaign stills'] },
  { slug: 'feel-every-frequency', title: 'Feel every frequency.', client: 'PULSE', industry: 'Technology', category: 'Product Films', tags: ['Product Films', 'Technology', 'Concept / Spec Work'], image: '/images/pulse-technology.jpg', accent: '#929aa5', description: 'Sound you can almost see. Precision you can feel.', brief: 'Create a premium audio product world that makes an invisible benefit—immersive sound—visually tangible.', challenge: 'Express the experience of sound while maintaining disciplined material rendering, realistic geometry, and a restrained premium aesthetic.', concept: 'The shape of sound. Liquid ripples and sweeping chrome forms respond to an imagined frequency, framing the headphones as an instrument of immersion.', deliverables: ['Product launch visual treatment', 'Material & detail studies', 'Retail display visuals', 'Social launch assets'] },
  { slug: 'made-for-momentum', title: 'Made for momentum.', client: 'STRIDE', industry: 'Sports', category: 'Commercials', tags: ['Commercials', 'Sports', 'Social Content', 'Concept / Spec Work'], image: '/images/momentum-sport.jpg', accent: '#c5e74b', description: 'Pure energy. Zero hesitation. A new perspective on performance.', brief: 'Explore a performance-footwear campaign that feels optimistic, energetic, and recognizably different from conventional sports advertising.', challenge: 'Capture energy in a controlled product composition while keeping shoe structure, material, and perspective believable.', concept: 'Potential, suspended. An acid-green running shoe hovers over a cobalt track: the fraction of a second before everything moves.', deliverables: ['Hero campaign key visual', 'Short-form motion treatments', 'Product detail variations', 'Multi-format campaign assets'] },
];

export const workFilters = ['All work', 'Commercials', 'Product Films', 'Brand Films', 'Social Content', 'Fashion', 'Beauty', 'Automotive', 'Food & Beverage', 'Technology', 'Sports', 'Concept / Spec Work'];
export const industries = [
  { slug: 'beauty', title: 'Beauty', description: 'Sensory storytelling. Beautifully precise products.', image: '/images/aura-beauty.jpg' },
  { slug: 'fashion', title: 'Fashion', description: 'New worlds for distinctive collections.', image: '/images/form-fashion.jpg' },
  { slug: 'automotive', title: 'Automotive', description: 'Extraordinary journeys. Unmistakable design.', image: '/images/vyra-hero.jpg' },
  { slug: 'food-beverage', title: 'Food & Beverage', description: 'A visual appetite for something different.', image: '/images/orange-beverage.jpg' },
  { slug: 'technology', title: 'Technology', description: 'Turn innovation into something people feel.', image: '/images/pulse-technology.jpg' },
  { slug: 'consumer', title: 'Consumer goods', description: 'Everyday products. Exceptional stories.', image: '/images/aura-beauty.jpg' },
  { slug: 'sports', title: 'Sports', description: 'All the energy. None of the ordinary.', image: '/images/momentum-sport.jpg' },
  { slug: 'ecommerce', title: 'E-commerce', description: 'Content that brings the product closer.', image: '/images/pulse-technology.jpg' },
  { slug: 'luxury', title: 'Luxury', description: 'A considered world. An elevated point of view.', image: '/images/form-fashion.jpg' },
];

export { insights, insightCategories, type Insight } from './insight-articles';
