import Link from 'next/link';
import Image from 'next/image';
import { Hero, ServicesAccordion } from '@/components/interactive';
import { ArrowRight, ArrowUpRight, Spark } from '@/components/icons';
import { ButtonLink, CTASection, InsightCard, ProjectCard, SectionLabel } from '@/components/ui';
import { industries, insights, projects } from '@/lib/site-data';

export default function HomePage() {
  return <>
    <div className="hero-wrap"><Hero /></div>
    <div className="manifesto-strip content-width"><span>IMAGINATION, MEET POSSIBILITY.</span><div><span>Creative at heart</span><Spark size={15} /><span>AI in our DNA</span><Spark size={15} /><span>Human in every frame</span></div><span className="strip-scroll">SCROLL TO EXPLORE <ArrowRight size={14} /></span></div>
    <section className="intro-section content-width"><SectionLabel number="01">THE VYRA DIFFERENCE</SectionLabel><div className="intro-grid"><h2>New possibilities.<br />Same obsession<br className="desktop-break" /> with the extraordinary<span className="accent-dot">.</span></h2><div className="intro-copy"><p className="lead">Great work has always started with a great idea.<br className="desktop-break" /> We just gave it a bigger canvas.</p><p>We’re an AI-native, human-directed production company creating commercials, brand films, and campaign content for a world that doesn’t stand still.</p><p>Less friction. More creative freedom.<br />All the craft that makes a film unforgettable.</p><Link href="/about" className="text-link">Meet a different kind of studio <ArrowUpRight size={18} /></Link></div></div></section>
    <section className="selected-work content-width"><div className="section-heading"><div><SectionLabel number="02">SELECTED WORK</SectionLabel><h2>Seeing is believing.</h2></div><ButtonLink href="/work" variant="outline">View all work <span className="button-count">06</span></ButtonLink></div><div className="work-grid home-work-grid">{projects.slice(0, 4).map((project, index) => <ProjectCard key={project.slug} project={project} index={index} />)}</div><div className="work-section-bottom"><span>BIG WORLDS. SMALL DETAILS. NO ORDINARY FRAMES.</span><span>A selection of VYRA concept studies.</span></div></section>
    <section className="services-section"><div className="content-width services-layout"><div className="services-intro"><SectionLabel number="03">WHAT WE PRODUCE</SectionLabel><h2>Made to move<br />your audience.<br /><span>And your brand.</span></h2><p>From one unforgettable film to an entire campaign ecosystem. Exceptional content, built around what you need to achieve.</p><ButtonLink href="/services" variant="outline">Explore our services</ButtonLink><Spark className="services-spark" size={110} /></div><ServicesAccordion /></div></section>
    <section className="human-section"><div className="content-width human-grid"><div className="human-visual"><Image src="/images/form-fashion.jpg" alt="Human-directed fashion concept with sculptural silk in a volcanic landscape" fill sizes="(max-width: 700px) 100vw, 50vw" /><div className="human-image-caption"><span>THE ART IS HUMAN.</span><Spark size={34} /><span>THE POSSIBILITIES ARE LIMITLESS.</span></div><div className="human-visual-label">HUMAN<br /><i>×</i> AI</div></div><div className="human-copy"><SectionLabel light number="04">OUR PRODUCTION DNA</SectionLabel><h2>Human imagination.<br /><span>Amplified.</span></h2><p>AI doesn’t replace creative judgment.<br />It gives it room to go further.</p><p className="muted">Our directors, artists, and producers combine emerging technology with time-honored craft. The right tools for every shot. A human point of view in every frame.</p><div className="human-values"><span>Creativity first.</span><span>Human directed.</span><span>Built to scale.</span></div><ButtonLink href="/process/technology" variant="text">Inside our production model</ButtonLink></div></div></section>
    <section className="home-process content-width"><div className="section-heading"><div><SectionLabel number="05">HOW WE WORK</SectionLabel><h2>From “what if” to “that’s it.”</h2></div><ButtonLink href="/process" variant="outline">Our full process</ButtonLink></div><div className="process-preview">{[
      { number: '01', title: 'Understand.', description: 'Your brand. Your audience. Your ambition. We begin with the right questions.' },
      { number: '02', title: 'Imagine.', description: 'Strong concepts and a distinct visual world. The idea comes first. Always.' },
      { number: '03', title: 'Create.', description: 'Human-led, AI-native production. Crafted, refined, and finished with care.' },
      { number: '04', title: 'Multiply.', description: 'One great idea, ready for every platform, audience, and market that matters.' },
    ].map(step => <div className="process-preview-card" key={step.number}><div><span>{step.number}</span><ArrowRight size={22} /></div><h3>{step.title}</h3><p>{step.description}</p></div>)}</div></section>
    <section className="scale-section"><div className="content-width"><div className="scale-heading"><SectionLabel>ONE IDEA. EVERY OPPORTUNITY.</SectionLabel><h2>Don’t just make a film.<br />Build a world of content.</h2><p>A single creative direction. An entire ecosystem of assets.<br />Designed for consistency. Built for scale.</p></div><div className="scale-diagram"><div className="scale-origin"><PlayMark /><span>ONE HERO FILM</span></div><div className="scale-connector"><ArrowRight size={32} /></div><div className="scale-outputs">{['Campaign cutdowns', 'Social-first content', 'Product assets', 'Localized versions', 'Audience variations', 'Every aspect ratio'].map((item, index) => <span key={item}><i>0{index + 1}</i>{item}<ArrowUpRight size={15} /></span>)}</div></div><Link href="/services/campaign-systems" className="text-link">Explore campaign content systems <ArrowUpRight size={18} /></Link></div></section>
    <section className="audience-section content-width"><SectionLabel number="06">GOOD COMPANY. GREAT COLLABORATIONS.</SectionLabel><div className="audience-grid"><Link href="/brands" className="audience-card audience-brands"><span className="eyebrow">FOR BRANDS</span><h2>Your ambition.<br />Our creative engine.</h2><p>Think of us as your external production department.<br />{' '}Ready to bring more of your brand’s potential to life.</p><span className="text-link">Build with VYRA <ArrowUpRight size={20} /></span><span className="audience-corner">B<span>↗</span></span></Link><Link href="/agencies" className="audience-card audience-agencies"><span className="eyebrow">FOR AGENCIES</span><h2>Your creative idea.<br />Our production engine.</h2><p>Behind your next great campaign. A white-label,<br />AI-native production partner that feels like your team.</p><span className="text-link">Partner with VYRA <ArrowUpRight size={20} /></span><span className="audience-corner">A<span>↗</span></span></Link></div></section>
    <section className="industries-strip content-width"><div><SectionLabel>NO INDUSTRY LIMITS.</SectionLabel><h3>Different worlds.<br />The same creative energy.</h3></div><div className="industry-links">{industries.map(industry => <Link key={industry.slug} href={`/industries/${industry.slug}`}>{industry.title}<ArrowUpRight size={14} /></Link>)}</div></section>
    <section className="home-insights content-width"><div className="section-heading"><div><SectionLabel number="07">FROM THE STUDIO</SectionLabel><h2>Ahead of the next frame.</h2></div><ButtonLink href="/insights" variant="outline">All insights</ButtonLink></div><div className="insights-grid">{insights.slice(0, 3).map(insight => <InsightCard key={insight.slug} insight={insight} />)}</div></section>
    <CTASection />
  </>;
}
function PlayMark() { return <div className="scale-play"><svg width="30" height="30" viewBox="0 0 30 30" fill="currentColor" aria-hidden="true"><path d="m11 7 14 8-14 8V7Z" /></svg></div>; }
